[package]
name = "sharc"
version = "0.1.0"
edition = "2021"
description = "The compiler for the Shard Programming Language."
license = "MIT"
repository = "https://github.com/shard-org/sharc"


[dependencies]
colored = "2.1"
