struct_field_align_threshold = 99
fn_params_layout = "Compressed"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
