name: Cargo
run-name: "Checks #${{ github.event.number }}"

on:
	pull_request:

		env:
			CARGO_TERM_COLOR: always

jobs:
	build:
		name: Check
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- run: rustup update nightly && rustup default nightly
			- run: cargo check 

	clippy:
		name: Clippy
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- run: rustup update nightly && rustup default nightly && rustup component add clippy
			- run: cargo clippy
