name: Cargo
run-name: "Checks #${{ github.event.number }}"

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
    build:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup update stable && rustup default stable
            - run: cargo check 

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup update stable && rustup default stable
            - run: cargo clippy
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup update stable && rustup default stable
            - run: cargo fmt --check
